[package]
name = "kit-thesis"
version = "0.1.0"
compiler = "0.14.2"
repository = "https://github.com/ll-nick/kit-thesis"
entrypoint = "lib.typ"
description = "Unofficial KIT dissertation / thesis template — KSP-compatible"
authors = ["Nick Le Large <https://github.com/ll-nick>"]
license = "MIT-0"
categories = ["thesis"]
disciplines = ["engineering", "computer-science"]
keywords = ["dissertation", "doctoral", "karlsruhe", "kit", "ksp"]

[template]
path = "template"
entrypoint = "main.typ"
thumbnail = "template/thumbnail.png"
